### ISSUE TITLE
Incorrect Access-Control-Allow-Origin header when `cors` option is function and no origin header is present

### ISSUE THREAD

**Issue by JamieCurnow** [NozomuIkuta/h3-cors#1]
Hello and thank you for making this helpful open source contribution 🙌

I'm testing this out in a Nuxt server-side h3 app and running into an error from h3:

`undefined is not allowed origin`

My situation is that I have defined the origin option as a function that returns a boolean. This works, however, I'm making a request from the browser to the same origin. This means that the browser does not add the `origin` header. So when your package calls `createOriginHeaders()`, it ends up trying to add `Access-Control-Allow-Origin` header as `undefined`.

```ts
export function createOriginHeaders (event: CompatibilityEvent, options: CorsOptions): AccessControlAllowOriginHeader {
  const { origin } = options // origin here is a function 🙈

  if (!origin || origin === '*') {
    return { 'Access-Control-Allow-Origin': '*' }
  }

  if (typeof origin === 'string') {
    return { 'Access-Control-Allow-Origin': origin, Vary: 'Origin' }
  }

  const requestOriginHeader = getRequestHeader(event, 'Origin') as string // requestOriginHeader is actually undefined! 😬
  const headers = Array.isArray(requestOriginHeader) ? requestOriginHeader.join(',') : requestOriginHeader

  return { 'Access-Control-Allow-Origin': headers, Vary: 'Origin' }
}
```

As you are checking the origin function to see if it is allowed before the code gets to this point, I think you can just assume that if `requestOriginHeader` is undefined, then it should be '*'. Or potentially if `requestOriginHeader` is undefined then you should return an empty object?

PR incoming...

**Comment by nozomuikuta** [comment]
Ref for future: https://stackoverflow.com/questions/42239643/when-do-browsers-send-the-origin-header-when-do-browsers-set-the-origin-to-null/42242802
