### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by Baroshem** [NozomuIkuta/h3-cors#3]
Great work!

I wanted to implement CORS middleware from scratch in my recently created Nuxt Module (https://github.com/Baroshem/nuxt-security) and then I have found your H3 Handler that does that perfectly

You can follow it here if you like -> https://github.com/Baroshem/nuxt-security/issues/3

I will make sure to mention your package in my module so that you can get more traction :)

**Comment by Baroshem** [comment]
Do you maybe have some recommendations on what configuration can I set to your package inside of my module so that most users will benefit? With my module, I am setting some default values for certain middlewares so that the user would only have to import and register the module and it will automacally work for him (but still, user can customize everything via config).

**Comment by nozomuikuta** [comment]
Hi, thank you for considering the use of my package 😄 🙌 

> Do you maybe have some recommendations on what configuration can I set to your package inside of my module so that most users will benefit?

To be honest, it depends on the situation: 

- What kind of resources the owner of the web application want to protect from and make public 
- to which requester (_Origins_)
- for what kind of operations (_Methods_)

But, generally speaking, resource-mutating operations like `POST` etc. would be likely to be made available only to the same origin for security reasons.
